#!/bin/bash
set - x

virt-install --connect=qemu:///system \
    --network=bridge:virbr1 \
    --extra-args="ks=http://192.168.1.144/ks.cfg \
      console=tty0 console=ttyS0,115200 edd=off" \
    --name=Minecraft \
    --disk /var/lib/libvirt/images/minecraft.img,size=10 \
    --ram 2048 \
    --vcpus=2 \
    --graphics none \
    --location=/opt/mirror/centos/CentOS-6.6-x86_64-bin-DVD1.iso
