#!/bin/bash
echo "####################" > /home/adam/scripts/dump.txt
date +%c >> /home/adam/scripts/dump.txt
echo "####################" >> /home/adam/scripts/dump.txt
who -q >>  /home/adam/scripts/dump.txt
echo "####################" >> /home/adam/scripts/dump.txt
cat /home/adam/scripts/dump.txt
